const fs = require('fs');
let s = fs.readFileSync('index.html', 'utf8');

const fnStartStr = 'function assignmentPlacementOverviewMarkup(rec,perm,entity,ctx){';
const nextFnStartStr = 'function assignmentTempOverviewMarkup(rec,perm,entity,ctx){';

const startIdx = s.indexOf(fnStartStr);
const endIdx = s.indexOf(nextFnStartStr);

if (startIdx !== -1 && endIdx !== -1) {
    const correctFn = `function assignmentPlacementOverviewMarkup(rec,perm,entity,ctx){
let owner=A.lu.users[rec.assigneeUserId],credits=pj(rec.recruiterCreditJson,[]),documents=assignmentJsonList(rec.documentsJson),timeline=assignmentTimelineItems(rec).slice(0,5),lifecycle=workbenchStageFlow(['Placed','Active','Completed'],rec.status||'Placed',\`\${rec.candidateName||ctx.candidate?.fullName||'-'} placed at \${rec.clientName||ctx.client?.name||'-'}\`),business=workbenchBusinessGrid([{label:'Assignment Code',value:rec.assignmentCode||rec.id},{label:'Candidate',value:rec.candidateName||ctx.candidate?.fullName||'-'},{label:'Job',value:rec.jobTitle||ctx.job?.title||'-'},{label:'Client',value:rec.clientName||ctx.client?.name||'-'},{label:'Placement Type',value:assignmentPlacementTypeLabel(rec.placementType)},{label:'Owner',value:owner?.fullName||'Unassigned'},{label:'Stage',value:rec.stageName||'Active'},{label:'Status',value:rec.status||'Placed'}]),commercial=workbenchFactGrid([{label:'Placement Fee',value:moneyVisible(rec.placementFee||0,rec.feeCurrency||'USD'),sub:'Total estimated revenue'},{label:'Invoice Status',value:rec.invoiceStatus||'Pending',sub:rec.invoiceDate?fmt(rec.invoiceDate):'Invoice date not set'},{label:'Payment Date',value:rec.paymentDate?fmt(rec.paymentDate):'-',sub:'Collected revenue'},{label:'Margin',value:rec.marginPct?\`\${rec.marginPct}%\`:'-',sub:'Gross margin percentage'}]),dateMeta=workbenchMetaList([{label:'Placement Date',value:fmt(rec.placementDate||rec.createdAt)},{label:'Start Date',value:fmt(rec.startDate)},{label:'End Date',value:fmt(rec.endDate)},{label:'Probation Date',value:fmt(rec.probationDate)}]),alignmentMarkup=assignmentCapabilityWorkspacePanel('Direct Placement'),creditRows=credits.length?workbenchPlainRows(credits.map(c=>({title:A.lu.users[c.userId]?.fullName||'Recruiter',meta:\`\${c.percent}%\`,sub:c.role||'Placement credit'})),'No split revenue recorded.'):'<div class="candemptyblock">No split revenue recorded.</div>',splitRows=credits.length?workbenchPlainRows(credits.filter(c=>c.percent>0&&c.userId!==rec.assigneeUserId).map(c=>({title:A.lu.users[c.userId]?.fullName||c.userId,meta:\`\${c.percent}% split\`,sub:'Secondary credit allocation'})),'No secondary stakeholders share credit.'):'<div class="candemptyblock">No secondary stakeholders share credit.</div>',documentRows=workbenchPlainRows(documents.map(item=>({title:item.name||'Document',meta:item.status||'Pending',sub:item.note||'Placement document'})),'No placement documents linked yet.'),timelineMarkup=workbenchFeed(timeline,'No placement activity captured yet.',timeline.length?{sub:'Open the timeline tab for the full history.',mod:'assignments',id:rec.id,tab:'timeline',label:'Open Timeline'}:null),actionsMarkup=assignmentQuickActionsMarkup(rec,perm,entity,'placement');
return \`<div class="candpage">\${candidatePanelMarkup('Placement Lifecycle',lifecycle)}\${candidatePanelMarkup('Business Card',business,'','candpanel-business')}\${candidatePanelMarkup('Closing Report', workbenchFactGrid([{ label: 'Candidate', value: rec.candidateName || ctx.candidate?.fullName || '-', sub: 'Placed candidate' }, { label: 'Role / Job', value: rec.jobTitle || ctx.job?.title || '-', sub: ctx.application?.applicationCode || '-' }, { label: 'Client', value: rec.clientName || ctx.client?.name || '-', sub: 'Hiring organization' }, { label: 'Salary', value: moneyVisible(rec.salary || 0), sub: 'Compensation package' }, { label: 'Start Date', value: fmt(rec.startDate), sub: 'Candidate joining date' }, { label: 'Recruiter Credit', value: credits.length ? credits.map(c => (A.lu.users[c.userId]?.fullName || 'Recruiter') + ' ' + c.percent + '%').join(', ') : 'Not assigned', sub: 'Revenue attribution' }]))}\${candidatePanelMarkup('Finance',commercial)}\${candidatePanelMarkup('Date & Notice',dateMeta)}\${candidatePanelMarkup('Bullhorn Alignment',alignmentMarkup)}\${candidatePanelMarkup('Recruiter Credit',creditRows)}\${candidatePanelMarkup('Split Fee Attribution',splitRows)}\${candidatePanelMarkup('Documents',documentRows)}\${candidatePanelMarkup('Recent Timeline',timelineMarkup)}\${candidatePanelMarkup('Quick Actions',actionsMarkup)}</div>\`
}
`;
    s = s.slice(0, startIdx) + correctFn + s.slice(endIdx);
    fs.writeFileSync('index.html', s);
    console.log('Fixed');
} else {
    console.error('Not found');
}
